### ISSUE TITLE
AttributeError: 'ALPR' object has no attribute 'conn'

### ISSUE THREAD

**Issue by JCAK1967** [ankandrew/ConvALPR#1]
Hola, buenas noches. Los felicito por el proyecto y estoy muy interesado en poder probarlo, pero no logro instalarlo correctamente o algo falta y no sé qué es.

Estoy probando el código sobre Ubuntu server 18.04.6 y estoy usando la versión de python 3.6.9

Lo primero que hice, fue instalar a mano las dependencias que figuran en _requirements.txt_ porque me encontré con un problema, que el release candidate de Tensorflow 2.3.0rc0 no existe más, así que instalé directamente el 2.3.0 con `pip install tensorflow-gpu==2.3.0`

El resto de la instalación no fue problema, no tuve ningún error.

Detalle importante, no estoy usando GPU, así que descomenté la línea `os.environ["CUDA_VISIBLE_DEVICES"] = "-1"` que según entiendo es la forma de indicar que no tengo GPU, por default entendí que el código viene para usar GPU, corríjanme si digo mal.

Al ejecutar cualquiera de las líneas que trae el ejemplo, me arroja el siguiente mensaje de error, por ejemplo cualquierda de las siguientes da el mismo error:

`python reconocedor_automatico.py --cfg config.yaml --demo`
`python3 reconocedor_automatico.py --cfg config.yaml`

error:
```
local variable 'cursor' referenced before assignment
Exception ignored in: <bound method SqlSaver.__del__ of <alpr.alpr.ALPR object at 0x7f736223abe0>>
Traceback (most recent call last):
  File "/opt/ConvALPR/alpr/saver.py", line 63, in __del__
    self.conn.commit()
AttributeError: 'ALPR' object has no attribute 'conn'

```
Por si sirve el dato, la carpeta de la base de datos la crea, pero la base no.

Por favor, si me pueden ayudar, no sé qué es lo que está faltando o qué pasos me recomiendan repasar para tratar de resolverlo.

Muchas gracias

**Comment by ankandrew** [comment]
Hola, gracias por interesarte en el proyecto!

> Lo primero que hice, fue instalar a mano las dependencias que figuran en _requirements.txt_ porque me encontré con un problema, que el release candidate de Tensorflow 2.3.0rc0 no existe más, así que instalé directamente el 2.3.0 con `pip install tensorflow-gpu==2.3.0`

Es verdad, la versión de TF `2.3.0rc0` **no existe** más. Ahí actualicé `requirements.txt`.

> Detalle importante, no estoy usando GPU, así que descomenté la línea `os.environ["CUDA_VISIBLE_DEVICES"] = "-1"` que según entiendo es la forma de indicar que no tengo GPU, por default entendí que el código viene para usar GPU, corríjanme si digo mal.

TensorFlow va a detectar automáticamente si tenés o no GPU, no debería de afectar esa linea. Armé un [Colab ](https://colab.research.google.com/drive/1FDCNjKADnmT5FLtf87n8VTEnHnMEZstR?usp=sharing) para replicar en ubuntu con python 3.7

> ```
> local variable 'cursor' referenced before assignment
> Exception ignored in: <bound method SqlSaver.__del__ of <alpr.alpr.ALPR object at 0x7f736223abe0>>
> Traceback (most recent call last):
>   File "/opt/ConvALPR/alpr/saver.py", line 63, in __del__
>     self.conn.commit()
> AttributeError: 'ALPR' object has no attribute 'conn'
> ```

No pude reproducirlo, si volves a correrlo con la ultima versión del repo, que error te tira? Te dice algo de error de permisos para escribir la db?

**Comment by JCAK1967** [comment]
Hola @ankandrew

Gracias por tu respuesta y por subir una actualización del código: Me demoré un poco en responder, porque me tome el tiempo para repetir los pasos e instalarlo sobre un 18.04.6 Desktop y también en Server. Armé PC virtuales en todos los casos y algo que omití comentar en mi mensaje anterior, que las pruebas las hice sobre el root pero también creando entornos virtuales en python. Esta vez, la prueba la hice directamente sobre el root, sin entornos viertuales, con Python3.7 tal como me indicaste y con una versión de pip3  21.3.1, ejecutando el siguiente comando

`python3.7 reconocedor_automatico.py --cfg config.yaml`

El resultado fue el siguiente mensaje:

_`No se encuentra el archivo de entrada (revisar config)`_

Otra prueba que hice, fue modificar el path en el archivo config, colocando el path completo al archivo jpg
En este último caso, el mensaje fue el siguiente:

```
_[ERROR:0] global /tmp/pip-req-build-3129w7z7/opencv/modules/videoio/src/cap.cpp (164) open VIDEOIO(CV_IMAGES): raised OpenCV exception:

OpenCV(4.5.4) /tmp/pip-req-build-3129w7z7/opencv/modules/videoio/src/cap_images.cpp:253: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file): ~/opt/ConvALPR/imgs/prueba.jpg in function 'icvExtractPattern'

No se encuentra el archivo de entrada (revisar config)_
```

La base de datos la crea, el esquema y la tabla también, pero sin datos.

Por último te cuento, hice la prueba añadiendo la opción --demo, que abre una ventana completamente en negro y se cierra rápidamente. El resultado es el mismo, mismos mensajes y sin datos en la base. No sé porque nunca lo vi funcionando, pero supongo que en esa ventana debería aparecer la imágen, o me equivoco. Tal vez falta alguna dependencia. Pregunto esto de las dependencias, porque me topé con que tuve que añadir algunas, que luego te comento para no confundirte en la resolución del caso.

Mientras aguardo tu respuesta seguiré probando cosas, reinstalando todo nuevamente, pero sinceramente no sé que más hacer.

Muchas gracias.

**Comment by JCAK1967** [comment]
Hola y gracias por preguntar. La respuesta corta es "No lo pude hacer andar" y lo dejé en donde te conté. Instalé la actualización que me pasaste y tal como escribí en mi post anterior, me la pase haciendo pruebas pero sin exito.
Esperé durante un tiempo luego de contarte los pasos que había realizado, a ver si se te ocurría algo más, pero como no tenia respuesta abordé otro proyecto y esto lo puse en StdBy.  Me sigue interesando tu desarrollo, por lo cual si hay alguna actualización para probar lo hago, aunque ahora estoy ajustado de tiempos pero sin apuro lo veo.
Desde ya muchas gracias.
Julio

> @JCAK1967 llegastes a encontrar la solucion para No se encuentra el archivo de entrada (revisar config)_

**Comment by eduardo1055433** [comment]
@JCAK1967  no soy el que se encargo de desarrollo , pero soy uno que esta probando la libreria , logre ejecutarla pero no funciona como quisiera yo , que otras alternativas encontrastes para la deteccion de placas ??, yo encontre SimpleLPR de warelogic aunque es de paga , me funciono para escapar del problema

**Comment by ankandrew** [comment]
@JCAK1967 @eduardo1055433 ahora miro bien el problema. =

**Comment by ankandrew** [comment]
@JCAK1967 @eduardo1055433 deberia de funcionar ahora. Borren el virtual env e instalen desde 0 porque actualice las versiones de las dependencias.

Probado con `Python 3.9`. Resultado de foto & video:

### Foto

```
python reconocedor_automatico.py --cfg config.yaml --demo
```

y en el `config.yaml` lo deje como viene.

![image](https://user-images.githubusercontent.com/61120139/172955410-9113131c-1c29-4673-826b-6e2ee87afd8b.png)

### Video

![image](https://user-images.githubusercontent.com/61120139/172955425-4a586eae-d086-447e-91e2-f35d7f5fe630.png)

```
python reconocedor_automatico.py --cfg config.yaml --demo
```

pero le cambie en `config,yaml` la fuente a: './assets/demo-vid.mp4'. Les dejo el video para que prueben:

https://user-images.githubusercontent.com/61120139/172956305-f355e7d3-a1c0-4211-8fe8-d113898b5b57.mp4


Cualquier cosa vuelvan abrir el issue
