### ISSUE TITLE
Patente no reconocida

### ISSUE THREAD

**Issue by GonzaloSP** [ankandrew/ConvALPR#5]
Hola,

Gracias por la implementación. Intentè ejecutarlo con [esta imagen](https://ibb.co/tsP7Zc4) y no la reconoce. Solo me funciona con la que viene en assets. Cuál puede ser el problema?
Estoy utilizando este còdigo para la prueba:

```
im = cv2.imread('patente_test.jpg')
with open('config.yaml', 'r') as stream:
    cfg = yaml.safe_load(stream)
alpr = ALPR(cfg['modelo'], cfg['db'])
predicciones = alpr.predict(im)
print(predicciones)
```

Gracias

**Comment by ankandrew** [comment]
Hola @GonzaloSP! Funciona mejor con las patentes que no están tan rotadas como la foto que me pasaste. Esto es porque cuando se entreno el reconocedor de texto, no se usaron fotos de esa naturaleza. Si querés contemplar estos escenarios no habría problema, podes juntar fotos de patentes y volver a entrenar el modelo con esta guía https://github.com/ankandrew/cnn-ocr-lp/wiki/Entrenamiento.

El localizador/reconocedor funciona bien, dentro de todo (no haría falta entrenar otro):
![image](https://user-images.githubusercontent.com/61120139/175833303-6a18df97-6ce9-48e1-a028-6491963bfa56.png)

**Comment by GonzaloSP** [comment]
Gracias @ankandrew . Tengo una serie de fotos que se toman de distintos ángulos por eso no están estandarizadas como con las que entrenaste el modelo. Crees que puedo rotar las imagenes del mismo dataset y volver a entrenarlo?

**Comment by ankandrew** [comment]
@GonzaloSP El repo `cnn-ocr-lp` no incluye la misma cantidad de imagenes con la que fue entrenado los modelos en este repo. Solo hay una muestra pequeña para que puedas corroborar que funciona el entrenamiento con tu entorno. Lo que podes hacer es juntar un dataset con el formato especificado [acá](https://github.com/ankandrew/cnn-ocr-lp/wiki/Entrenamiento.) y volver a entrenar. Si querés podes incluso compartir tus resultados en el otro repo!

Si queres rotar artificialmente, podes cambiar los valores que se encuentran acá https://github.com/ankandrew/cnn-ocr-lp/blob/4a7dd34c9803caada0dc50a33b59487b63dd4754/augmentation.py#L43-L52. Igualmente antes de entrenar para ver lo que el modelo va a usar para entrenamiento (que tenga sentido) lo podes hacer con esto https://github.com/ankandrew/cnn-ocr-lp/wiki/Entrenamiento#visualizar-data-augmentation
