### ISSUE TITLE
Lectura en tiempo real con http o rtsp camara ip

### ISSUE THREAD

**Issue by martinambrueso** [ankandrew/ConvALPR#7]
Buenas noches, espero esten bien.

Soy nuevo en este mundo, y me gustaria usar este modelo para obtener patentes en tiempo real, mediante una camara ip en vivo, via http o rtsp. Es posible?

Gracias

**Comment by ankandrew** [comment]
Hola! Si es posible. De hecho cualquier formato que soporte  [VideoCapture() ](https://docs.opencv.org/3.4/d8/dfe/classcv_1_1VideoCapture.html#a949d90b766ba42a6a93fe23a67785951), ejemplo de rtsp:

https://github.com/ankandrew/ConvALPR/blob/b6dcbeba32df3f96099a00660bf8baaf7ed3f3d6/config.yaml#L5-L6
